# Generated by Django 2.2 on 2019-10-30 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190426_0757'),
        ('core', '0002_auto_20191030_1142'),
    ]

    operations = [
    ]
