# Generated by Django 2.2 on 2019-11-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191101_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='types',
            field=models.CharField(choices=[('N', 'New'), ('B', 'Best Seller'), ('NY', 'NY Local'), ('S', 'Staff Pick'), ('P', 'Most Popular')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
