# Generated by Django 2.2 on 2019-11-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='types',
            field=models.CharField(choices=[('N', 'New'), ('B', 'Best Seller'), ('NY', 'NY Local'), ('S', 'Staff Pick'), ('P', 'Most Popular')], max_length=2, null=True),
        ),
    ]
