# Generated by Django 2.2 on 2019-11-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20191101_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='types',
            field=models.CharField(blank=True, choices=[('N', 'New'), ('B', 'Best Seller'), ('NY', 'NY Local'), ('S', 'Staff Pick'), ('P', 'Most Popular'), ('BL', '')], max_length=2, null=True),
        ),
    ]
