# Generated by Django 2.2 on 2019-11-22 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20191101_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='abv',
            field=models.CharField(choices=[('5', '5%'), ('12', '12%'), ('40', '40%'), ('8', '8%')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='features',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='region',
            field=models.CharField(choices=[('A', 'Asia'), ('E', 'England'), ('M', 'Mexico'), ('I', 'Italy'), ('A', 'France'), ('S', 'South Asia'), ('U', 'United States'), ('S', 'Spain'), ('R', 'Russia')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sizes',
            field=models.CharField(choices=[('S', '750ml'), ('M', '1L'), ('L', '1.75L'), ('XL', '375ml')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='tasting',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='types',
            field=models.CharField(choices=[('N', 'New'), ('B', 'Best Seller'), ('NY', 'NY Local'), ('S', 'Staff Pick'), ('P', 'Most Popular'), ('H', 'Holiday Pick'), ('BL', '')], max_length=2, null=True),
        ),
    ]
